version: "3"

services:
  my-sql:
    container_name: my-sql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Seoul
      volumes:
        -/db/mysql/data:/var/lib/mysql
        -/db/mysql/config:/etc/mysql/conf.d
        -/db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/data:/data
    ports:
      - "6379:6379"

  was-blue:
    container_name: was-blue
    image: phj2784/sleep-well:GITHUB_SHA
    restart: always
    volumes:
      - /sleep-well/logs:/sleep-well/logs  # log 보존
    ports:
      - "8080:8080"
    env_file:
      - /sleep-well/.env
    depends_on:
      - redis
      - my-sql
