version: "3"

services:
  was-blue:
    container_name: sleep-well-blue
    image: phj2784/sleep-well:GITHUB_SHA
    restart: always
    volumes:
      - /sleep-well/logs:/sleep-well/logs  # log 보존
    ports:
      - "8080:8080"
    env_file:
      - ../.env
