version: "3"

services:
  my-sql:
    container_name: my-sql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: Asia/Seoul
      volumes:
        -/db/mysql/data:/var/lib/mysql
        -/db/mysql/config:/etc/mysql/conf.d
        -/db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - /etc/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /redis/data:/data
    ports:
      - "6379:6379"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../var/log/nginx:/var/log/nginx
    depends_on:
      - sleep-well-blue

  sleep-well-blue:
    container_name: sleep-well-blue
    image: phj2784/sleep-well:GITHUB_SHA
    restart: always
    volumes:
      - /sleep-well/logs:/sleep-well/logs  # log 보존
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - redis
      - my-sql
