name: develop CD

on:
  push:
    branches: [ be/feature/practice-cd-flow ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: install jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: assign gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot application and create executable JAR file
        run: ./gradlew bootJar

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: make docker images
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/sleep-well:${{ github.sha }} -f ./docker/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/sleep-well:${{ github.sha }}

      - name: make docker-compose files
        run: |
          sed -i "s/GITHUB_SHA/${{ github.sha }}/g" ./docker/docker-compose-init.yml

      - name: make BE .env
        run: |
          echo "${{ secrets.BE_ENV }}" > .env

      - name: send files & deploy script
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".env,docker/docker-compose-init.yml,deploy.sh"
          target: ./sleep-well
          overwrite: true

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/sleep-well:${{ github.sha }}
            cd ./sleep-well/docker
            chmod +x ./deploy.sh
            ./deploy.sh
